# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc
stages:
  - build
  - run
build:
  stage: build
  script:
    - source /opt/intel/bin/compilervars.sh intel64
    - make
  artifacts:
    paths:
      - stable-marriage-cpu
      - stable-marriage-st
      - stable-marriage-complete-cpu
      - stable-marriage-complete-st
  cache:
    paths:
      - "*.o"
run:
  stage: run
  artifacts:
    paths:
      - host
  script:
    - source /opt/intel/bin/compilervars.sh intel64
    - mkdir -p host/easy host/hard
    - ./stable-marriage-cpu ~/sm-datasets/manWomanGraph_10000000_10000000_340007576.dat | tee host/easy/10000000_10000000_340007576.results.txt
    - ./stable-marriage-st ~/sm-datasets/manWomanGraph_10000000_10000000_340007576.dat | tee host/easy/results_10000000_10000000_340007576_singlethreaded_results.txt
    - ./stable-marriage-cpu ~/sm-datasets/manWomanGraph_20000000_20000000_709985096.dat | tee host/easy/20000000_20000000_709985096.results.txt
    - ./stable-marriage-st ~/sm-datasets/manWomanGraph_20000000_20000000_709985096.dat | tee host/easy/results_20000000_20000000_709985096_singlethreaded_results.txt
    - ./stable-marriage-cpu ~/sm-datasets/manWomanGraph_40000000_40000000_1480074907.dat | tee host/easy/40000000_40000000_1480074907.results.txt
    - ./stable-marriage-st ~/sm-datasets/manWomanGraph_40000000_40000000_1480074907.dat | tee host/easy/results_40000000_40000000_1480074907_singlethreaded_results.txt
    - ./stable-marriage-cpu ~/sm-datasets/manWomanGraph_50000000_50000000_1849916651.dat | tee host/easy/50000000_50000000_1849916651.results.txt
    - ./stable-marriage-st ~/sm-datasets/manWomanGraph_50000000_50000000_1849916651.dat | tee host/easy/results_50000000_50000000_1849916651_singlethreaded_results.txt
    - ./stable-marriage-cpu ~/sm-datasets/manWomanGraph_60000000_60000000_2220111233.dat | tee host/easy/60000000_60000000_2220111233.results.txt
    - ./stable-marriage-st ~/sm-datasets/manWomanGraph_60000000_60000000_2220111233.dat | tee host/easy/results_60000000_60000000_2220111233_singlethreaded_results.txt
    - ./stable-marriage-cpu ~/sm-datasets/manWomanGraph_75000000_75000000_2887538634.dat | tee host/easy/75000000_75000000_2887538634.results.txt
    - ./stable-marriage-st ~/sm-datasets/manWomanGraph_75000000_75000000_2887538634.dat | tee host/easy/results_75000000_75000000_2887538634_singlethreaded_results.txt
    - ./stable-marriage-cpu ~/sm-datasets/manWomanGraph_100000000_100000000_3850014406.dat | tee host/easy/100000000_100000000_3850014406.results.txt
    - ./stable-marriage-st ~/sm-datasets/manWomanGraph_100000000_100000000_3850014406.dat | tee host/easy/results_100000000_100000000_3850014406_singlethreaded_results.txt
    - ./stable-marriage-cpu ~/sm-datasets/manWomanGraph_125000000_125000000_4812489007.dat | tee host/easy/125000000_125000000_4812489007.results.txt
    - ./stable-marriage-st ~/sm-datasets/manWomanGraph_125000000_125000000_4812489007.dat | tee host/easy/results_125000000_125000000_4812489007_singlethreaded_results.txt
    - ./stable-marriage-complete-cpu 100000 ~/sm-datasets/ranking_100000_100000.dat | tee host/hard/100000_complete.results.txt
    - ./stable-marriage-complete-st 100000 ~/sm-datasets/ranking_100000_100000.dat | tee host/hard/100000_complete_singlethreaded.results.txt
    - ./stable-marriage-complete-cpu 200000 ~/sm-datasets/ranking_200000_200000.dat | tee host/hard/200000_complete.results.txt
    - ./stable-marriage-complete-st 200000 ~/sm-datasets/ranking_200000_200000.dat | tee host/hard/200000_complete_singlethreaded.results.txt
    - ./stable-marriage-complete-cpu 300000 ~/sm-datasets/ranking_300000_300000.dat | tee host/hard/300000_complete.results.txt
    - ./stable-marriage-complete-st 300000 ~/sm-datasets/ranking_300000_300000.dat | tee host/hard/300000_complete_singlethreaded.results.txt
    - ./stable-marriage-complete-cpu 400000 ~/sm-datasets/ranking_400000_400000.dat | tee host/hard/400000_complete.results.txt
    - ./stable-marriage-complete-st 400000 ~/sm-datasets/ranking_400000_400000.dat | tee host/hard/400000_complete_singlethreaded.results.txt
    - ./stable-marriage-complete-cpu 500000 ~/sm-datasets/ranking_500000_500000.dat | tee host/hard/500000_complete.results.txt
    - ./stable-marriage-complete-st 500000 ~/sm-datasets/ranking_500000_500000.dat | tee host/hard/500000_complete_singlethreaded.results.txt
    - ./stable-marriage-complete-cpu 600000 ~/sm-datasets/ranking_600000_600000.dat | tee host/hard/600000_complete.results.txt
    - ./stable-marriage-complete-st 600000 ~/sm-datasets/ranking_600000_600000.dat | tee host/hard/600000_complete_singlethreaded.results.txt